In [6]:
import pandas as pd

#df = pd.read_csv('star_classification.csv')
df = pd.read_csv("D:\College\Sem 7\ProjectPhase1\CERN_PySR\dielectron.csv")
df = df.round(2)
df.head(10)

,Run,Event,E1,px1,py1,pz1,pt1,eta1,phi1,Q1,E2,px2,py2,pz2,pt2,eta2,phi2,Q2,M
0,147115,366639895,58.71,-7.31,10.53,-57.30,12.82,-2.20,2.18,1,11.28,-1.03,-1.88,-11.08,2.15,-2.34,-2.07,-1,8.95
1,147115,366704169,6.61,-4.15,-0.58,-5.11,4.19,-1.03,-3.00,-1,17.15,-11.71,5.04,11.46,12.75,0.81,2.73,1,15.89
2,147115,367112316,25.54,-11.48,2.04,22.72,11.66,1.42,2.97,1,15.82,-1.47,2.26,-15.59,2.70,-2.46,2.15,1,38.39
3,147115,366952149,65.40,7.51,11.89,63.87,14.06,2.22,1.01,1,25.13,4.09,2.60,24.66,4.84,2.33,0.57,-1,3.73
4,147115,366523212,61.45,2.95,-14.62,-59.61,14.92,-2.09,-1.37,-1,13.89,-0.28,-2.43,-13.67,2.44,-2.42,-1.68,-1,2.75
5,147115,366663412,6.40,-5.46,-2.09,-2.60,5.84,-0.43,-2.78,-1,21.39,15.17,-8.87,-12.19,17.57,-0.65,-0.53,-1,18.40
6,147115,366639101,84.51,8.82,10.58,83.38,13.78,2.50,0.88,1,12.68,-1.13,-3.21,-12.21,3.40,-1.99,-1.91,-1,65.32
7,147115,367133576,77.01,10.00,9.18,-75.80,13.57,-2.42,0.74,1,9.12,-1.72,-1.49,-8.83,2.28,-2.06,-2.43,1,11.29
8,147115,368639137,9.69,1.11,2.05,-9.40,2.33,-2.10,1.07,1,63.46,-1.86,12.79,-62.13,12.93,-2.27,1.72,1,3.59
9,147115,367825395,27.88,11.94,-18.35,17.27,21.89,0.72,-0.99,1,12.92,-5.03,11.60,2.66,12.64,0.21,1.98,-1,34.27